export const SET_ADMIN_PENDING_STATUS = 'SET_ADMIN_PENDING_STATUS'

export const PENDING_STATUS_API_ERROR = 'PENDING_STATUS_API_ERROR'

export const IS_APPLICATION_STATUS_PENDING = 'IS_APPLICATION_STATUS_PENDING'