export const SET_APPLICATIONS = 'SET_APPLICATIONS'
export const GET_APPLICATIONS_API_ERROR = 'GET_APPLICATIONS_API_ERROR'
export const IS_GET_APPLICATIONS_PENDING = 'IS_GET_APPLICATIONS_PENDING'

export const SET_APPLICATION_DETAIL = 'SET_APPLICATION_DETAIL'
export const GET_APPLICATION_DETAIL_API_ERROR =
  'GET_APPLICATION_DETAIL_API_ERROR'
export const IS_GET_APPLICATION_DETAIL_PENDING =
  'IS_GET_APPLICATION_DETAIL_PENDING'

export const CREATE_APPLICATION_API_ERROR = 'CREATE_APPLICATION_API_ERROR'
export const IS_CREATE_APPLICATION_PENDING = 'IS_CREATE_APPLICATION_PENDING'

export const UPDATE_APPLICATION_API_ERROR = 'UPDATE_APPLICATION_API_ERROR'
export const IS_UPDATE_APPLICATION_PENDING = 'IS_UPDATE_APPLICATION_PENDING'

export const UPDATE_STATUS_API_ERROR = 'UPDATE_STATUS_API_ERROR'
export const IS_UPDATE_STATUS_PENDING = 'IS_UPDATE_STATUS_PENDING'
