export const SET_NEW_APPLICATION_DATA = 'SET_NEW_APPLICATION_DATA';

export const NEW_APPLICATION_API_ERROR = 'NEW_APPLICATION_API_ERROR';

export const IS_NEW_APPLICATION_DATA_PENDING = 'IS_NEW_APPLICATION_DATA_PENDING';