export const SET_RECENT_APPLICATION_DATA = 'SET_RECENT_APPLICATION_DATA';

export const RECENT_APPLICATION_API_ERROR = 'RECENT_APPLICATION_API_ERROR';

export const IS_RECENT_APPLICATION_DATA_PENDING = 'IS_RECENT_APPLICATION_DATA_PENDING';